version: 2
updates:
    - package-ecosystem: "gradle"
      directories:
        - "/"
        - "/gradle/*.versions.toml"
      schedule:
          interval: "daily"
      groups:
          gradle-updates:
              patterns:
                  - "*"
