version: 2
registries:
    teamresourceful:
        type: maven-repository
        url: https://maven.teamresourceful.com/repository/maven-public/
updates:
    -   package-ecosystem: gradle
        directory: /
        schedule:
            interval: daily
        allow:
            -   dependency-name: "tech.thatgravyboat:skyblock-api"
